providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1675123887'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
[phases.build]
dependsOn = ['install']
cmds = ['']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci']
cacheDirectories = ['/root/.npm']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'python38',
    'nodejs',
    'gnat',
]
nixLibs = []
nixOverlays = []
nixpkgsArchive = '293a28df6d7ff3dec1e61e37cc4ee6e6c0fb0847'
aptPkgs = []

[start]
cmd = 'echo $CONFIG_JSON > ./config.json && node index.js'

